Stats page to use the new get_stats view method
0LNetworkCommunity/explorer pull request #25
Opened 2024-04-22 14:14 UTC by hemulin

2024-04-22 22:25 UTC, willrnch requested changes

2024-04-22 22:25 UTC, willrnch commented on api/src/stats/stats.service.ts
> +import fetch from 'node-fetch';
please use `axios` instead

2024-04-22 22:30 UTC, minaxolone requested changes

2024-04-22 22:30 UTC, minaxolone commented on api/package.json
> +    "node-fetch": "^3.3.2",
please use `axios` instead.

2024-04-23 20:37 UTC, minaxolone approved these changes

2024-04-23 20:37 UTC, merged